name: Traefik
version: 5.0.1
slug: traefik
description: |
  Traefik is a modern HTTP reverse proxy and load balancer that makes deploying
  microservices easy.
breaking_versions:
  - 5.0.0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
init: false
stage: stable
boot: auto
url: https://github.com/mikeomat/home-assistant-addons/tree/master/traefik
ports:
  80/tcp: 80
  443/tcp: 443
  8080/tcp: 8080
ports_description:
  80/tcp: HTTP
  443/tcp: HTTPS
  8080/tcp: Web Interface
# The dashboard does not load fully
# when using ingress.
#ingress: true
#ingress_entry: dashboard/
#ingress_port: 8080
discovery:
  - traefik
hassio_role: default
hassio_api: true
panel_icon: mdi:earth-arrow-right
map:
  - homeassistant_config
  - ssl:rw
options:
  log_level: info
  access_logs: false
  forwarded_headers_insecure: false
  insecure_skip_verify: false
  dynamic_configuration_path: "/homeassistant/traefik/"
  letsencrypt:
    enabled: false
    resolvers: []
  env_vars: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  access_logs: bool
  forwarded_headers_insecure: bool
  insecure_skip_verify: bool
  dynamic_configuration_path: str
  letsencrypt:
    enabled: bool
    email: email?
    challenge_type: match(tlsChallenge|httpChallenge|dnsChallenge)?
    ca_server: str?
    provider: str?
    delayBeforeCheck: int?
    resolvers:
      - str?
  env_vars:
    - str
